name: book_on
description: An application for tracking and saving read books.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0
  flutter_bloc: ^7.1.0
  bloc: ^7.1.0
  font_awesome_flutter: ^9.1.0

  shared_preferences: ^2.0.7

  intl: ^0.17.0
  easy_localization: ^3.0.0
  image_picker: ^0.8.3+3
  equatable: ^2.0.3
  meta: ^1.4.0
  formz: ^0.4.0
  google_fonts: ^2.1.0
  rflutter_alert: ^2.0.4

  google_sign_in: ^5.1.0

  cloud_firestore: ^2.5.1
  firebase_storage: ^10.0.5
  firebase_core: ^1.7.0
  firebase_auth: ^3.1.0
  carousel_slider: ^4.0.0
  share: ^2.0.4
  rotated_corner_decoration: ^2.0.0
  syncfusion_flutter_gauges: ^19.2.60
  fl_chart: ^0.40.0
  flex_color_scheme: ^3.0.1  
  connectivity: ^3.0.6
  moor_flutter: ^4.0.0
  uuid: ^3.0.4
  fancy_bottom_navigation: ^0.3.3
  searchfield: ^0.5.6
  cupertino_icons: ^1.0.2
  jiffy: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^8.3.0
  mockito: ^5.0.11
  build_runner: ^2.1.2
  moor_generator: ^4.4.1
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo_new.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_new.png
    - assets/translations/
    - assets/images/quotes_bg/1.jpg
    - assets/images/quotes_bg/2.jpg
    - assets/images/quotes_bg/3.jpg
    - assets/images/quotes_bg/4.jpg
    - assets/images/quotes_bg/5.jpg
    - assets/images/quotes_bg/6.jpg

  fonts:
    - family: RussoOne
      fonts:
        - asset: assets/fonts/RussoOne-Regular.ttf
    - family: MontserratAlternates
      fonts:
        - asset: assets/fonts/MontserratAlternates-Regular.ttf

